package router

import (
	"comicfun/internal/handler"
	"comicfun/internal/middleware"

	"github.com/gin-gonic/gin"
)

func Setup(r *gin.Engine) {
	api := r.Group("/api")
	{
		api.GET("/health/check", handler.Health)
		api.GET("/system/check", handler.CheckSystemInitialized)
		api.POST("/user/init", handler.Init)
		api.POST("/user/login", handler.Login)

		auth := api.Group("").Use(middleware.AuthRequired())
		{
			auth.GET("/system/statistics", handler.GetStatistics)
			auth.GET("/user/me", handler.GetMe)
			auth.PUT("/user/profile", handler.UpdateProfile)
			auth.PUT("/user/password", handler.UpdatePassword)
			auth.POST("/upload/avatar", handler.UploadAvatar)
			auth.GET("/artifact/list", handler.ListArtifacts)
			auth.GET("/tag/list", handler.ListTags)
			auth.GET("/tag/get/:id", handler.GetTag)
			auth.GET("/bookmark/list", handler.ListBookmarks)
			auth.GET("/bookmark/status/:artifactId", handler.GetBookmarkStatus)
			auth.POST("/bookmark/add", handler.AddBookmark)
			auth.DELETE("/bookmark/remove/:artifactId", handler.RemoveBookmark)
			auth.POST("/history/update", handler.UpdateHistory)
			auth.GET("/history/get/:artifactId", handler.GetHistory)
			auth.GET("/history/list", handler.ListHistory)
			auth.DELETE("/history/delete/:artifactId", handler.DeleteHistory)
			auth.DELETE("/history/clear", handler.ClearHistory)
			auth.GET("/novel/list", handler.ListNovels)
			auth.GET("/comic/list", handler.ListComics)
			auth.GET("/animation/list", handler.ListAnimations)
			auth.GET("/novel/get/:id", handler.GetNovel)
			auth.GET("/comic/get/:id", handler.GetComic)
			auth.GET("/animation/get/:id", handler.GetAnimation)
			auth.GET("/novel/:id/structure", handler.GetNovelStructure)
			auth.GET("/comic/:id/structure", handler.GetComicStructure)
			auth.GET("/animation/:id/structure", handler.GetAnimationStructure)
			auth.GET("/novel/chapter/:chapterId", handler.GetChapter)
			auth.GET("/comic/chapter/:chapterId", handler.GetComicChapter)
			auth.GET("/comic/:id/export", handler.ExportComicChapter)
			auth.GET("/animation/chapter/:chapterId", handler.GetAnimationChapter)
			auth.GET("/animation/:id/export", handler.ExportAnimationChapter)
			auth.GET("/novel/:id/export/txt", handler.ExportNovelTxt)
		}

		admin := api.Group("").Use(middleware.AuthRequired(), middleware.AdminRequired())
		{
			admin.POST("/tag/create", handler.CreateTag)
			admin.PUT("/tag/update/:id", handler.UpdateTag)
			admin.DELETE("/tag/delete/:id", handler.DeleteTag)
			admin.POST("/upload/tag-image", handler.UploadTagImage)
			admin.POST("/upload/cover", handler.UploadCover)
			admin.POST("/upload/comic-page/:artifactId/:volumeId/:chapterId", handler.UploadComicPage)
			admin.GET("/user/list", handler.ListUsers)
			admin.POST("/user/create", handler.CreateUser)
			admin.PUT("/user/update/:id", handler.UpdateUser)
			admin.DELETE("/user/delete/:id", handler.DeleteUser)
			admin.POST("/user/reset-password/:id", handler.ResetPassword)
			admin.GET("/acl/artifact/:artifact_id", handler.GetArtifactACL)
			admin.PUT("/acl/artifact/:artifact_id", handler.UpdateArtifactACL)
			admin.GET("/acl/users", handler.GetRegularUsers)
			admin.POST("/novel/create", handler.CreateNovel)
			admin.PUT("/novel/update/:id", handler.UpdateNovel)
			admin.DELETE("/novel/delete/:id", handler.DeleteNovel)
			admin.GET("/novel/:id/volumes", handler.ListVolumes)
			admin.POST("/novel/:id/volume/create", handler.CreateVolume)
			admin.PUT("/novel/volume/:volumeId", handler.UpdateVolume)
			admin.DELETE("/novel/volume/:volumeId", handler.DeleteVolume)
			admin.GET("/novel/volume/:volumeId/chapters", handler.ListChapters)
			admin.POST("/novel/volume/:volumeId/chapter/create", handler.CreateChapter)
			admin.PUT("/novel/chapter/:chapterId", handler.UpdateChapter)
			admin.DELETE("/novel/chapter/:chapterId", handler.DeleteChapter)
			admin.POST("/comic/create", handler.CreateComic)
			admin.PUT("/comic/update/:id", handler.UpdateComic)
			admin.DELETE("/comic/delete/:id", handler.DeleteComic)
			admin.GET("/comic/:id/volumes", handler.ListComicVolumes)
			admin.POST("/comic/:id/volume/create", handler.CreateComicVolume)
			admin.PUT("/comic/volume/:volumeId", handler.UpdateComicVolume)
			admin.DELETE("/comic/volume/:volumeId", handler.DeleteComicVolume)
			admin.GET("/comic/volume/:volumeId/chapters", handler.ListComicChapters)
			admin.POST("/comic/volume/:volumeId/chapter/create", handler.CreateComicChapter)
			admin.PUT("/comic/chapter/:chapterId", handler.UpdateComicChapter)
			admin.DELETE("/comic/chapter/:chapterId", handler.DeleteComicChapter)
			admin.GET("/comic/chapter/:chapterId/pages", handler.ListComicPages)
			admin.POST("/comic/chapter/:chapterId/page/create", handler.CreateComicPage)
			admin.POST("/comic/chapter/:chapterId/pages/batch", handler.BatchCreateComicPages)
			admin.PUT("/comic/page/:pageId", handler.UpdateComicPage)
			admin.POST("/comic/page/:pageId/move", handler.MoveComicPage)
			admin.DELETE("/comic/page/:pageId", handler.DeleteComicPage)
			admin.POST("/upload/video/:artifactId/:volumeId/:chapterId", handler.UploadVideo)
			admin.POST("/animation/create", handler.CreateAnimation)
			admin.PUT("/animation/update/:id", handler.UpdateAnimation)
			admin.DELETE("/animation/delete/:id", handler.DeleteAnimation)
			admin.GET("/animation/:id/volumes", handler.ListAnimationVolumes)
			admin.POST("/animation/:id/volume/create", handler.CreateAnimationVolume)
			admin.PUT("/animation/volume/:volumeId", handler.UpdateAnimationVolume)
			admin.DELETE("/animation/volume/:volumeId", handler.DeleteAnimationVolume)
			admin.GET("/animation/volume/:volumeId/chapters", handler.ListAnimationChapters)
			admin.POST("/animation/volume/:volumeId/chapter/create", handler.CreateAnimationChapter)
			admin.PUT("/animation/chapter/:chapterId", handler.UpdateAnimationChapter)
			admin.DELETE("/animation/chapter/:chapterId", handler.DeleteAnimationChapter)
		}
	}
}
